p8105_hw2_yx2858
================
Yueyi Xu
2023-10-01

``` r
library(tidyverse) #load library tidyverse
library(dplyr)
```

# Problem 1

# Problem 2

``` r
Wheel_df =
  readxl::read_excel("202309 Trash Wheel Collection Data.xlsx",
  sheet = "Mr. Trash Wheel",   #read the dataset with sheet and range
  range = "A2:N586") |>
  janitor::clean_names() |>   #clean the names
  drop_na("dumpster") |>   #omit na values
  mutate(homes_powered = weight_tons*500/30,   #calculate the homes_powered variable
         year = as.integer(year),   #change to numerical variable
         additional_dataset = "Mr. Trash")   #specify the dataset
```

#### Description of Wheel_df:

This Wheel_df dataset contains 584 observations and dumpster, month,
year, date, weight_tons, volume_cubic_yards, plastic_bottles,
polystyrene, cigarette_butts, glass_bottles, plastic_bags, wrappers,
sports_balls, homes_powered, additional_dataset variables. The variable
“homes_powered” is calculated using the existing variable “weight_tons”
to determine each ton of trash equates to, on average 500 kilowatts of
electricity an average household will use 30 kilowatts per day. The
additional variable of “additional_dataset” specifies the corresponding
data to the “Mr. Trash” category. This way, after merging the three
datasets, “Mr. Trash” will be easily distinguished from the rest.

``` r
Professor_df =
  readxl::read_excel("202309 Trash Wheel Collection Data.xlsx",
  sheet = "Professor Trash Wheel",   #read the dataset with sheet and range
  range = "A2:M108") |>
  janitor::clean_names() |>   #clean the names
  drop_na("dumpster") |>   #omit na values
  mutate(homes_powered = weight_tons*500/30,   #calculate the homes_powered variable
         additional_dataset = "Professor Trash")   #specify the dataset
```

#### Description of Professor_df:

This Professor_df dataset contains 106 observations and dumpster, month,
year, date, weight_tons, volume_cubic_yards, plastic_bottles,
polystyrene, cigarette_butts, glass_bottles, plastic_bags, wrappers,
homes_powered, additional_dataset variables. The total weight of trash
collected by Professor Trash Wheel is 216.26 tons. The variable
“homes_powered” is calculated using the existing variable “weight_tons”
to determine each ton of trash equates to, on average 500 kilowatts of
electricity an average household will use 30 kilowatts per day. The
additional variable of “additional_dataset” specifies the corresponding
data to the “Professor Trash” category. This way, after merging the
three datasets, “Professor Trash” will be easily distinguished from the
rest.

``` r
Gwynnda_df = 
  readxl::read_excel("202309 Trash Wheel Collection Data.xlsx",
  sheet = "Gwynnda Trash Wheel",   #read the dataset with sheet and range
  range = "A2:L157") |>
  janitor::clean_names() |>   #clean the names
  drop_na("dumpster") |>   #omit na values
  mutate(homes_powered = weight_tons*500/30,   #calculate the homes_powered variable
         additional_dataset = "Gwynnda Trash")   #specify the dataset
```

``` r
Gwynnda_cigarette =
  filter(Gwynnda_df, month == "July" & year == 2021)
  sum(Gwynnda_cigarette$cigarette_butts)
```

    ## [1] 16300

#### Description of Gwynnda_df:

This Gwynnda_df dataset contains 155 observations and dumpster, month,
year, date, weight_tons, volume_cubic_yards, plastic_bottles,
polystyrene, cigarette_butts, plastic_bags, wrappers, homes_powered,
additional_dataset variables. The total number of cigarette butts
collected by Gwynnda in July of 2021 is 1.63^{4}. The variable
“homes_powered” is calculated using the existing variable “weight_tons”
to determine each ton of trash equates to, on average 500 kilowatts of
electricity an average household will use 30 kilowatts per day. The
additional variable of “additional_dataset” specifies the corresponding
data to the “Gwynnda Trash” category. This way, after merging the three
datasets, “Gwynnda Trash” will be easily distinguished from the rest.

``` r
Combine_TrashWheel = 
  bind_rows(Wheel_df, Professor_df, Gwynnda_df)   #combine three datasets
```

#### Description of Combine_TrashWheel:

This dataset combines three datasets of Wheel_df, Professor_df, and
Gwynnda_df with a total of 845 observations and dumpster, month, year,
date, weight_tons, volume_cubic_yards, plastic_bottles, polystyrene,
cigarette_butts, glass_bottles, plastic_bags, wrappers, sports_balls,
homes_powered, additional_dataset variables. The additional variable of
“additional_dataset” specifies each of the three corresponding
categories.

# Problem 3

``` r
baseline_mci_df = 
  read_csv("data_mci/MCI_baseline.csv", skip = 1, na = ".") |>   #read the dataset as na
  janitor::clean_names() |>   #clean the names
  mutate(   #mutate sex and apoe4 variables
    sex = replace(sex, sex == 0, "Female"),
    sex = replace(sex, sex == 1, "Male"), 
    apoe4 = replace(apoe4, apoe4 == 1, "Yes"),
    apoe4 = replace(apoe4, apoe4 == 0, "No")
  ) |>   
  filter(!(current_age >= age_at_onset | is.na(age_at_onset)))   #remove the participants who don't develop MCI or have already developed MCI before the study
```

``` r
baseline_recruited_df = 
  read_csv("data_mci/MCI_baseline.csv", skip = 1, na = ".") |>   #read the dataset as na
  janitor::clean_names() |>   #clean the names
  mutate(   #mutate sex and apoe4 variables
    sex = replace(sex, sex == 0, "Female"),
    sex = replace(sex, sex == 1, "Male"), 
    apoe4 = replace(apoe4, apoe4 == 1, "Yes"),
    apoe4 = replace(apoe4, apoe4 == 0, "No")
  )  
  filter(baseline_recruited_df, current_age < age_at_onset | is.na(age_at_onset))   #keep the participants who develop or do not develop MCI, i.e. remove the participants who have already developed MCI before the study
```

    ## # A tibble: 479 × 6
    ##       id current_age sex    education apoe4 age_at_onset
    ##    <dbl>       <dbl> <chr>      <dbl> <chr>        <dbl>
    ##  1     1        63.1 Female        16 Yes           NA  
    ##  2     2        65.6 Female        20 Yes           NA  
    ##  3     3        62.5 Male          16 Yes           66.8
    ##  4     4        69.8 Female        16 No            NA  
    ##  5     5        66   Male          16 No            68.7
    ##  6     6        62.5 Male          16 No            NA  
    ##  7     7        66.5 Male          18 No            74  
    ##  8     8        67.2 Female        18 No            NA  
    ##  9     9        66.7 Female        16 No            NA  
    ## 10    10        64.1 Female        18 No            NA  
    ## # ℹ 469 more rows

``` r
Average_age =
  pull(baseline_recruited_df, current_age)
  mean(Average_age)   #calculate the mean of the baseline age
```

    ## [1] 65.04679

``` r
filter(baseline_recruited_df, sex == "Female" & apoe4 == "Yes")   #select females who are apoe4 carriers
```

    ## # A tibble: 63 × 6
    ##       id current_age sex    education apoe4 age_at_onset
    ##    <dbl>       <dbl> <chr>      <dbl> <chr>        <dbl>
    ##  1     1        63.1 Female        16 Yes           NA  
    ##  2     2        65.6 Female        20 Yes           NA  
    ##  3    22        67.3 Female        20 Yes           74.6
    ##  4    26        64.8 Female        20 Yes           71.1
    ##  5    34        64.8 Female        16 Yes           NA  
    ##  6    39        68.3 Female        16 Yes           70.2
    ##  7    43        67.1 Female        16 Yes           71.6
    ##  8    47        66.1 Female        12 Yes           NA  
    ##  9    50        67.6 Female        18 Yes           NA  
    ## 10    52        63.2 Female        16 Yes           NA  
    ## # ℹ 53 more rows

``` r
filter(baseline_recruited_df, sex == "Female")   #select females
```

    ## # A tibble: 211 × 6
    ##       id current_age sex    education apoe4 age_at_onset
    ##    <dbl>       <dbl> <chr>      <dbl> <chr>        <dbl>
    ##  1     1        63.1 Female        16 Yes           NA  
    ##  2     2        65.6 Female        20 Yes           NA  
    ##  3     4        69.8 Female        16 No            NA  
    ##  4     8        67.2 Female        18 No            NA  
    ##  5     9        66.7 Female        16 No            NA  
    ##  6    10        64.1 Female        18 No            NA  
    ##  7    11        69.5 Female        16 No            NA  
    ##  8    12        66.2 Female        18 No            NA  
    ##  9    14        58.4 Female        20 No            66.2
    ## 10    16        64.9 Female        16 No            NA  
    ## # ℹ 201 more rows

Proportion calculation: 63/211 = 0.298 = 29.8%

#### Description of the important steps:

There were 479 participants recruited for this study. Of these
recruited, 93 participants develop MCI. The average baseline age is
65.04679 years old. 29.8% of women in the study are APOE4 carriers.
